# Generated by Django 3.1.5 on 2021-01-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
