# Generated by Django 3.1.5 on 2021-01-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_technologies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('technologies', models.ManyToManyField(help_text='Technologies used in the project', to='home.Technologies')),
            ],
        ),
    ]
