# Generated by Django 3.1.5 on 2021-01-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210122_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='img',
            new_name='image',
        ),
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
