# Generated by Django 3.1.5 on 2021-01-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210122_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Tool',
            new_name='tool',
        ),
        migrations.RemoveField(
            model_name='bio',
            name='avatar',
        ),
        migrations.AddField(
            model_name='bio',
            name='image',
            field=models.ImageField(null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='bio',
            name='bio',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bio',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='language',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='language',
            name='image',
            field=models.ImageField(null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tool',
            name='image',
            field=models.ImageField(null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
