# Generated by Django 3.1.5 on 2021-01-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210123_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='image_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='image_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='image_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='image_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
