# Generated by Django 3.1.5 on 2021-01-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210123_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='bio',
        ),
        migrations.AddField(
            model_name='bio',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='short_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='short_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='short_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='short_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
