# Generated by Django 3.1.5 on 2021-01-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210123_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='image',
            field=models.ImageField(null=True, upload_to='home/static/images'),
        ),
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(null=True, upload_to='home/static/images'),
        ),
        migrations.AlterField(
            model_name='language',
            name='image',
            field=models.ImageField(null=True, upload_to='home/static/images'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='image',
            field=models.ImageField(null=True, upload_to='home/static/images'),
        ),
    ]
